# Generated by Django 3.1.8 on 2021-07-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medspa', '0005_auto_20210729_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='picture',
            new_name='image',
        ),
    ]
