# Generated by Django 3.1.8 on 2021-07-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medspa', '0007_membership_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
