# Generated by Django 3.1.8 on 2021-08-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medspa', '0009_auto_20210801_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='detail',
            field=models.CharField(max_length=200),
        ),
    ]
